# Generated by Django 3.1 on 2021-08-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(max_length=255)),
                ('dono_loja', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('data', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('cpf', models.CharField(max_length=255)),
                ('cartao', models.CharField(max_length=255)),
                ('hora', models.CharField(max_length=255)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='api.store')),
            ],
        ),
    ]
